apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test
data:
  test.js: |
    import http from 'k6/http';
    export let options = {
      stages: [
        { duration: "5m", target: 50 },
      ],
    };
    export default function() {
      let response = http.get("http://service1:9091/");
    };

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k6
  labels:
    account: k6

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6
  labels:
    app: k6
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6
  template:
    metadata:
      labels:
        app: k6
        version: 1.0.0
    spec:
      serviceAccountName: k6
      containers:
        - name: k6
          image: loadimpact/k6:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: k6-test
              mountPath: /tmp/k6-test
          args:
          - "run"
          - "/tmp/k6-test/test.js"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: k6-test
          configMap:
            name: k6-test