deployment:
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
  pullPolicy: IfNotPresent
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi

goserver:
  b3Trace: true
  requestSize: 50
  responseSize: 50
  # serverName: (default to hostname = pod name in k8s)
  serverPort: 9091
  upstreamHost: service2
  upstreamPort: 9092
  verbose: true

service:
  account: service1
  name: service1
  portName: http-service1
  version: 1.0.0
