deployment:
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
  pullPolicy: IfNotPresent
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi

goserver:
  b3Trace: true
  requestSize: 50
  responseSize: 50
  # serverName: (default to hostname = pod name in k8s)
  serverPort: 9093
  upstreamHost: service4
  upstreamPort: 9094
  verbose: true

service:
  account: service3
  name: service3
  portName: http-service3
  version: 1.0.0
