deployment:
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
  pullPolicy: IfNotPresent
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
  affinity:
    node: {}
    pod: {}
    pod_anti: {}
  tolerations: []
  nodeSelector: []

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

goserver:
  b3Trace: false
  json: true
  requestSize: 50
  responseSize: 50
  # serverName: (default to hostname = pod name in k8s)
  serverPort: 9090
  upstreamHost: service2
  upstreamPort: 9090
  verbose: false

service:
  account: service1
  name: service1
  portName: http-service1
  version: 1.0.0
