---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
        version: 1.0.0
    spec:
      containers:
        - name: goserver
          image: boeboe/goserver:1.0.0
          imagePullPolicy: Always
          ports:
            - name: goserver
              containerPort: 9090
          env:
            - name: B3_TRACE
              value: true
            - name: REQUEST_SIZE
              value: 100
            - name: RESPONSE_SIZE
              value: 500
            - name: SERVER_PORT
              value: 9090
            - name: VERBOSE
              value: true
