---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
        version: 1.0.0
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: goserver
      containers:
        - name: goserver
          image: boeboe/goserver-scratch:1.0.0
          imagePullPolicy: Always
          ports:
            - name: goserver
              containerPort: 9090
          env:
            - name: B3_TRACE
              value: "true"
            - name: REQUEST_SIZE
              value: "100"
            - name: RESPONSE_SIZE
              value: "500"
            - name: SERVER_PORT
              value: "9090"
            - name: UPSTREAM_HOST
              value: ""
            - name: UPSTREAM_PORT
              value: "9090"
            - name: VERBOSE
              value: "true"
          livenessProbe:
            httpGet:
              path: "/health"
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: "/health"
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
