
---
apiVersion: v1
kind: Service
metadata:
  name: goserver
  labels:
    app: goserver
    version: 1.0.0
spec:
  type: NodePort
  ports:
    - name: http-goserver
      port: 9090
      targetPort: goserver
      nodePort: 30090
  selector:
    app: goserver
